#!/bin/bash
./uninstall

cp simple-file-server.conf /etc/init

mkdir /etc/simple-file-server
cp SimpleHTTPServerWithUploadAndAuthentication.py /etc/simple-file-server
cp settings.py /etc/simple-file-server

service simple-file-server start

echo "installation completed!"
echo "check simple-file-server at localhost:"$PORT
